### ISSUE TITLE
Holding a container with too much data crashes the game

### ISSUE THREAD

**Issue by SpaceChuck** [A5b84/held-item-info#3]
If you hold a container with too much data, it will crash the game. I tried holding a Dispenser with 9 stacks of Fireworks and it crashed the game.

Here's the log:
 [18:27:50] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'boolean net.minecraft.class_2487.isEmpty()'
	at io.github.a5b84.helditeminfo.ItemInfo.appendContainerContent(ItemInfo.java:294) ~[held-item-info-1.1.3.jar:?]
	at io.github.a5b84.helditeminfo.ItemInfo.buildInfo(ItemInfo.java:92) ~[held-item-info-1.1.3.jar:?]
	at net.minecraft.class_329.handler$bhb000$onAfterTick(class_329.java:2600) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_329.method_1748(class_329.java:1308) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1692) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1083) ~[intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-fabric-loader-0.11.3-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]

**Comment by A5b84** [comment]
Looks like this is the same issue as #4, I'll just close this one
